#!/usr/bin/env bash

function delayedPluginInstall {
    sudo mkdir -p /home/developer/.IdeaIC2016.3/config/plugins
    sudo mkdir -p /home/developer/.IdeaIC2016.3/config/options
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.3

    cd /home/developer/.IdeaIC2016.3/config/plugins/

    echo 'Installing Cursive plugin'
    wget https://plugins.jetbrains.com/files/8090/31467/cursive-1.4.3-2016.3.zip -O cursive.zip -q  && unzip -q cursive.zip && rm cursive.zip

    echo 'Installing Markdown support plugin'
    wget https://plugins.jetbrains.com/files/7793/32455/markdown-2016.3.20170209.zip -O markdown.zip -q && unzip -q markdown.zip && rm markdown.zip

    # Adding the predefined preferences to IDEA
    cp /home/developer/.jdk.table.xml /home/developer/.IdeaIC2016.3/config/options/jdk.table.xml
}

if [ ! -d /home/developer/.IdeaIC2016.3/config/plugins/clojure-plugin ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

if [ -d /home/developer/.IdeaIC2016.3 ]; then
    # Ensure proper permissions
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.3
fi

exec /opt/intellij/bin/idea.sh
